# Generated by Django 3.2 on 2021-04-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac', models.CharField(max_length=10)),
                ('issue_date', models.DateTimeField()),
                ('imms', models.CharField(max_length=10)),
                ('qty', models.IntegerField(default=0)),
                ('uom', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('issue_date',),
            },
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac', models.CharField(max_length=10)),
                ('po_date', models.DateTimeField()),
                ('imms', models.CharField(max_length=10)),
                ('qty', models.IntegerField(default=0)),
                ('uom', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('po_date',),
            },
        ),
    ]
