# Generated by Django 3.2 on 2021-04-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='start_date',
            field=models.DateField(),
        ),
    ]
