# Generated by Django 3.2 on 2021-04-08 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210407_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olditem',
            name='loum',
        ),
    ]
