# Generated by Django 3.2 on 2021-04-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_olditem_loum'),
    ]

    operations = [
        migrations.AddField(
            model_name='olditem',
            name='luom',
            field=models.CharField(default='EA', max_length=10),
        ),
        migrations.AlterField(
            model_name='newitem',
            name='loum',
            field=models.CharField(default='EA', max_length=10),
        ),
    ]
